server:
  port: ${SONG_SERVICE_PORT:8081}
  error:
    include-binding-errors: always
    include-message: always

spring:
  application.name: song-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/song-db}
    username: ${SONG_DB_USER:postgres}
    password: ${SONG_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa.hibernate.ddl-auto: none
  jpa.properties.dialect: org.hibernate.dialect.PostgreSQLDialect