server:
  port: 8081
  error:
    include-binding-errors: always
    include-message: always

spring:
  application.name: song-service

  datasource:
    url: jdbc:postgresql://localhost:5433/song-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa.hibernate.ddl-auto: update
  jpa.properties.dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa.defer-datasource-initialization: true
  sql.init.mode: always