spring:
  application:
    name: eureka-server
server:
  port: ${DISCOVERY_SERVICE_PORT:8761}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    preferIpAddress: true
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF